FROM alpine:latest
# Default command, can be overridden by docker run
CMD ["echo", "hello from CMD"]


# Run Example:
    
# docker build -t cmdtest .
# docker run --rm cmdtest
# # Output: hello from CMD

# docker run --rm cmdtest echo override
# # Output: override