apiVersion: v1
kind: Pod
metadata:
  name: live-config-volume-pod
spec:
  containers:
  - name: app
    image: busybox:latest
    command: ["sh", "-c", "while true; do cat /etc/config/message; sleep 5; done"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: live-config
