FROM alpine:latest
# Always run echo, user input as args
ENTRYPOINT ["echo", "entrypoint says:"]


# Run Examples:

# docker build -t entrytest .
# docker run --rm entrytest hello ENTRYPOINT
# # Output: entrypoint says: hello ENTRYPOINT

# docker run --rm entrytest Howdy
# # Output: entrypoint says: Howdy